DROP TABLE IF EXISTS activities;

CREATE TABLE  ACTIVITIES (
id INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(50) NOT NULL,
content VARCHAR(256) NOT NULL,
image VARCHAR(256) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
deleted BOOLEAN NOT NULL DEFAULT 0
);